import { PDFDocument, StandardFonts, rgb, degrees } from 'pdf-lib';
import fs from 'fs';

export const addWatermarkToPdf = async(pdfPath) => {
  // Read the PDF file
  const pdfBytes = fs.readFileSync(pdfPath);
  
  // Load the PDF document
  const pdfDoc = await PDFDocument.load(pdfBytes);
  
  // Get the pages
  const pages = pdfDoc.getPages();
  
  // Load a standard font
  const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  
  // Watermark text
  const watermarkText = 'PandaPrep AI';
  
  // Add watermark to each page
  for (const page of pages) {
    const { width, height } = page.getSize();
    
    // Center of the page
    const centerX = width / 2;
    const centerY = height / 2;
    
    // Text options for diagonal watermark
    page.drawText(watermarkText, {
      x: centerX - 200,
      y: centerY + 150,
      font: helveticaFont,
      size: 80,
      opacity: 0.2,
      color: rgb(0.75, 0.75, 0.75),
      rotate: degrees(-45),
    });
    
    // Add footer watermark
    page.drawText('Generated by PandaPrep AI', {
      x: width / 2 - 75,
      y: 30, // Position at bottom
      font: helveticaFont,
      size: 10,
      opacity: 0.8,
      color: rgb(0.5, 0.5, 0.5),
    });
  }
  
  // Serialize the PDFDocument to bytes
  const watermarkedPdfBytes = await pdfDoc.save();
  
  // Write the PDF to a file
  fs.writeFileSync(pdfPath, watermarkedPdfBytes);
  
  return pdfPath;
}